### ISSUE TITLE
no-ip.org

### ISSUE THREAD

**Issue by iLLiac4** [felmoltor/noip.autorenew#4]
it seems that this script is not working anymore. At least i did not update my hosts on my account. It has said succeed but on the web page it was still expire in 6 days.

**Comment by celem** [comment]
Works for me - shows a login each week. I use the **Ruby** version with this script in /etc/cron.weekly:

#! /bin/bash
#  /etc/cron.weekly/z-noipautorenew

# Script noip.autorenew - renews No-Ip.com DDNS
# See: https://github.com/felmoltor/noip.autorenew
#  Runs "/home/dzrmo/bin/noip.autorenew.rb"

export LOG=/tmp/noip.autorenew.log
export NOIPUSERNAME="mynoiplogin"
export NOIPPASSWORD=mynoippassword
export EMAILSERVER=smtp.mail.yahoo.com
export EMAILUSERNAME="myaccountname@yahoo.com"
export EMAILPASSWORD=myemailpassword

echo "---------------------------------------------"  > $LOG
echo "Output from " noip.autorenew  >> $LOG
/home/dzrmo/bin/noip.autorenew.rb $NOIPUSERNAME $NOIPPASSWORD  >> $LOG
echo "---------------------------------------------"  >> $LOG

sendEmail -f $EMAILUSERNAME -t $EMAILUSERNAME \
 -u "Results of noip.autorenew" \
 -o -o message-file=$LOG \
 -s $EMAILSERVER -xu $EMAILUSERNAME -xp $EMAILPASSWORD >> $LOG

exit 0

**Comment by iLLiac4** [comment]
I am using noip.autorenew.pl version and it seems not to update.

**Comment by iLLiac4** [comment]
I have now tested pl script and it says that it has updated successfuly but if i login into the no-ip page i still see expire in 6 days. Could i troubleshoot this or. should i give you my logins details to try to see what is wrong?

**Comment by felmoltor** [comment]
It seems that no-ip doesn't mind the host IP has been updated "manually" in your panel. It happens for all, not only for you, they are forcing to click on their email link to avoid this kind of automation. 
The script used to work, but not now.
I'll mark this project as not working anymore and leave it for educational purpouses.

Thank you for colaborating.
