### ISSUE TITLE
"No longer working"

### ISSUE THREAD

**Issue by kocane** [felmoltor/noip.autorenew#6]
How come this is "no longer working"? I've had it on my server for a good while and it have just run every once in a while with a cron. Right now my noip.me domain is expiring in 29 days...

How come?!

**Comment by celem** [comment]
The Ruby version (noip.autorenew.rb) works perfectly on my Linux system. I cannot comment on the Pearl version.

**Comment by felmoltor** [comment]
@kocane, As the note in the README says "This script used to work some time ago, now no-ip doesn't mind that you "manually" update your hosts, they will force to click in their email link to renew the expiration date. I'll leave this project here for educational purposes".

NoIP uses a reCaptcha to avoid robots and scripts updating automatically  domains, so this is why "no longer working" was introduced in the project README. This scripts uses mechanize gem to simulate a person clicking on links and therefore, it depends on the server HTML interface to keep working properly, if the web interface changes, then the script should also adapt to the web layout change.

You are invited to improve the script if you what. Make a fork of the project, verify that it works and then if you want to collaborate, execute a "pull request" to this repository.

**Comment by kocane** [comment]
@felmoltor I guess my question was poorly written. The script works just fine on my system and I'm wondering why, since - like you say - it shouldn't be possible?

**Comment by celem** [comment]
FYI - the script below works perfectly for me. It resides in /etc/cron.weekly and runs the ruby version on noip.autorenew, sending me an email as a success/fail indicator:
------------------

#! /bin/bash

# Script noip.autorenew - renews No-Ip.com DDNS
# See: https://github.com/felmoltor/noip.autorenew
#  Runs "/home/username/bin/noip.autorenew.rb"

export LOG=/tmp/noip.autorenew.log
export NOIPUSERNAME="username@yahoo.com"
export NOIPPASSWORD=yournoippassword
export EMAILSERVER=smtp.mail.yahoo.com
export EMAILUSERNAME="username@yahoo.com"
export EMAILPASSWORD=youremailpassword

echo "---------------------------------------------"  > $LOG
echo "Output from " noip.autorenew  >> $LOG
/home/username/bin/noip.autorenew.rb $NOIPUSERNAME $NOIPPASSWORD  >> $LOG
echo "---------------------------------------------"  >> $LOG

sendEmail -f $EMAILUSERNAME -t $EMAILUSERNAME \
 -u "Results of noip.autorenew" \
 -o -o message-file=$LOG \
 -s $EMAILSERVER -xu $EMAILUSERNAME -xp $EMAILPASSWORD >> $LOG


exit 0
