### ISSUE TITLE
Will it work again?

### ISSUE THREAD

**Issue by vincentkenny01** [felmoltor/noip.autorenew#7]
hi I have used your script previously and it worked well. Is there anyway you can make it work again?

**Comment by celem** [comment]
This project is DEAD. If you are running Linux, NOIP now offers a free DNS Updater of their own. 
See: [https://www.noip.com/download?page=linux](url)

**Comment by JanOonk** [comment]
But does this prevent the monthly mails, in which I have to click a link to confirm my hostname is still active (besides upgrading to paid version)?
